### PR TITLE
switch to a layout similar to NSLS-II / CSX beam line

### LINKED ISSUE #148: use ipython layout similar to NSLS-II/CSX
The CSX beam line at NSLS-II uses bluesky.  The structure and layout of its [ipython startup directory](https://github.com/NSLS-II-CSX/xf23id1_profiles/tree/master/profile_collection/startup) is different than ours.

### APS XPCS layout

```
startup/
    00-0-checks.py
    00-logging.py
    00-startup-jup.py
    00-startup.py
    01-databroker.py
    02-pyepics.py
    09-imports.py
    09-overrides.py
    10-devices.py
    11-device-overrides.py
    15-spec-config.py
    20-detectors.py
    21-signals.py
    26-lambda.py
    26-rigaku.py
    35-DM-support.py
    50-controls.py
    60-metadata.py
    80-callbacks.py
```

### NSLS-II CSX layout

```
startup/
    00-nsls2-tools.py
    csx1
        analysis
            __init__.py
        devices
            __init__.py
            areadetector.py
            devices.py
            eps.py
            epu.py
            lakeshore.py
            optics.py
            scaler.py
            stats_plugin.py
        plans
            __init__.py
            dark_ff.py
            nanop.py
            qplans.py
            xpcs.py
        startup
            __init__.py
            accelerator.py
            detectors.py
            endstation.py
            optics.py
            settings.py
            startup.py
            suspenders.py
            tardis.py
```

The instrument scientist reports this is much easier to understand and manage.

### PR DESCRIPTION
**Pull request by prjemian**
fixes #148

### CODE REVIEW

**Comment by prjemian** [comment]
We should test this as part of the review process.

**Comment by qzhang234** [comment]
@prjemian This looks good to me. What should I do? Should I initiate the merge request?

**Comment by prjemian** [comment]
Let's test first

**Comment by prjemian** [comment]
@gwbischof is still getting credit for commits from the beam line workstations.  We need to change that.

**Comment by prjemian** [comment]
@qzhang234 , @sureshnaps - `bluesky8IDI` starts a session with no errors.  Have not tested yet by operating any hardware.  Spot-checked that the devices are created and look right.  We should test this by using it as a user and make sure that all the plans are working.

**Comment by prjemian** [comment]
Ok, found something not working right:  `%run -m lambda_testing`

```
In [13]: %run -m lambda_testing                                                                                                                                                                         
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-e1044fef00a7> in <module>
----> 1 get_ipython().run_line_magic('run', '-m lambda_testing')

~/.conda/envs/bluesky/lib/python3.7/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2315                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2316             with self.builtin_trap:
-> 2317                 result = fn(*args, **kwargs)
   2318             return result
   2319 

</home/beams/8IDIUSER/.conda/envs/bluesky/lib/python3.7/site-packages/decorator.py:decorator-gen-59> in run(self, parameter_s, runner, file_finder)

~/.conda/envs/bluesky/lib/python3.7/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

~/.conda/envs/bluesky/lib/python3.7/site-packages/IPython/core/magics/execution.py in run(self, parameter_s, runner, file_finder)
    687         if "m" in opts:
    688             modulename = opts["m"][0]
--> 689             modpath = find_mod(modulename)
    690             if modpath is None:
    691                 warn('%r is not a valid modulename on sys.path'%modulename)

~/.conda/envs/bluesky/lib/python3.7/site-packages/IPython/utils/module_paths.py in find_mod(module_name)
     60     """
     61     loader = importlib.util.find_spec(module_name)
---> 62     module_path = loader.origin
     63     if module_path is None:
     64         return None

AttributeError: 'NoneType' object has no attribute 'origin'

```

**Do not merge yet.**

**Comment by prjemian** [comment]
Something is wrong with the `%run` magic.  In 28f1c5d, simplified the code loaded by `%run -m lambda_testing` to just a `print` and the `%run` magic fails:

```
In [1]: %run -m lambda_testing                                                                                                                                                                          
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-e1044fef00a7> in <module>
----> 1 get_ipython().run_line_magic('run', '-m lambda_testing')

~/.conda/envs/bluesky/lib/python3.7/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2315                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2316             with self.builtin_trap:
-> 2317                 result = fn(*args, **kwargs)
   2318             return result
   2319 

</home/beams/8IDIUSER/.conda/envs/bluesky/lib/python3.7/site-packages/decorator.py:decorator-gen-59> in run(self, parameter_s, runner, file_finder)

~/.conda/envs/bluesky/lib/python3.7/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

~/.conda/envs/bluesky/lib/python3.7/site-packages/IPython/core/magics/execution.py in run(self, parameter_s, runner, file_finder)
    687         if "m" in opts:
    688             modulename = opts["m"][0]
--> 689             modpath = find_mod(modulename)
    690             if modpath is None:
    691                 warn('%r is not a valid modulename on sys.path'%modulename)

~/.conda/envs/bluesky/lib/python3.7/site-packages/IPython/utils/module_paths.py in find_mod(module_name)
     60     """
     61     loader = importlib.util.find_spec(module_name)
---> 62     module_path = loader.origin
     63     if module_path is None:
     64         return None

AttributeError: 'NoneType' object has no attribute 'origin'
```

**Comment by prjemian** [comment]
Investigated offline, on other workstations, then retested just now and no problem now.  

```
In [2]: %run -m lambda_testing                                                                                           
I Wed-09:09:20 - /home/beams/8IDIUSER/.ipython-bluesky/user/lambda_testing.py

```

Must have been a transient problem.  Will revert to new preamble (28f1c5d1e6) ...

**Comment by prjemian** [comment]
Found the *transient problem*.  This call:
    zz

returns `/home/beams10/8IDIUSER/.ipython`
but it *should* be`/home/beams10/8IDIUSER/.ipython-bluesky`

Refactor the algorithm in `instrument/frameworks/user_dir.py()`

**Comment by prjemian** [comment]
[Back In The Saddle Again](https://www.youtube.com/watch?v=rSqcxFGFVas) and ready for testing and demo.  **Then**, if approved, merge.

**Comment by prjemian** [comment]
Note:

The *root cause* of the failure of `IPython.paths.get_ipython_dir()` to locate the correct directory is because the shell's environment variable was defined *locally*:

```
CONDA_ENVIRONMENT=bluesky
CONDA_ACTIVATE=/APSshare/miniconda/x86_64/bin/activate
IPYTHON_DIR=~/.ipython-bluesky
IPYTHON_PROFILE=bluesky
```

Should be defined with an `export` to the values can pass to the ipython session:

```
export CONDA_ENVIRONMENT=bluesky
export CONDA_ACTIVATE=/APSshare/miniconda/x86_64/bin/activate
export IPYTHON_DIR=~/.ipython-bluesky
export IPYTHON_PROFILE=bluesky
```

Also, note that `IPYTHON_DIR` is deprecated and will generate a notice from ipython.  Switch to `IPYTHONDIR` now.

**Comment by prjemian** [comment]
[Demonstrated](https://github.com/aps-8id-dys/ipython-8idiuser/pull/149#issuecomment-585358067):

```
In [1]: import IPython.paths

In [2]: IPython.paths.get_ipython_dir()
Out[2]: '/home/beams/8IDIUSER/.ipython-bluesky'
```

**Comment by qzhang234** [comment]
@prjemian This looks good to me. Is this revised/reorganized version ready to be deployed?

**Comment by prjemian** [comment]
Almost.  [Testing and demo](https://github.com/aps-8id-dys/ipython-8idiuser/pull/149#issuecomment-585285349) first.

**Comment by prjemian** [comment]
This is ready to merge.  @qzhang234, if you agree, please press the green *Merge pull request* button.

**Comment by prjemian** [comment]
The lockdown has interrupted our train of thought.  We should merge this, then test and demo as (re)learning exercises.

**Comment by qzhang234** [comment]
Pete:

Miaoqi figured out a way to calculate g2 100 times faster than the XPCS-Eigen (C++ on a single GPU) and all of us are in a meeting right now going over the details. By the way this code will eliminate the need of running DM workflow since the analysis is faster than the acquisition/sparsification (at least before APS-U). As a result I will likely skip the weekly meeting this week.

Please don't tell the xi-cam people about this development yet.

I will approve the merge once I'm out of the meeting.

Thanks,


QZ

________________________________

**Comment by sureshnaps** [comment]
Pete,
Please dis-regard the below email from Qingteng with regard to the obsolescence of DM workflows.
Suresh

**Comment by prjemian** [comment]
Thanks for the merge!

**Pull request merged**
